---
- name: Set Debian defaults
  ansible.builtin.set_fact:
    cron_daily: /etc/cron.daily/
    etc_prefix: ""
    install_prefix: /opt
  when: ansible_os_family == "Debian"

- name: Set FreeBSD default
  ansible.builtin.set_fact:
    cron_daily: /usr/local/etc/periodic/daily/
    etc_prefix: /usr/local
    install_prefix: /usr/local
  when: ansible_os_family == "FreeBSD"

- name: Set OpenBSD default
  ansible.builtin.set_fact:
    etc_prefix: ""
  when: ansible_os_family == "OpenBSD"
