---
# Currently no other defaults needed for "OpenBSD" or "RedHat"
- name: Set defaults
  ansible.builtin.set_fact:
    etc_prefix: ""
  when: >
    ansible_os_family == "Alpine"
    or ansible_os_family == "Debian"
    or ansible_os_family == "OpenBSD"
    or ansible_os_family == "RedHat"

- name: Set Debian defaults
  ansible.builtin.set_fact:
    cron_daily: /etc/cron.daily/
    # bash supports pipefail option, sh on Debian not.
    default_shell: /bin/bash
    install_prefix: /opt
  when: ansible_os_family == "Debian"

- name: Set FreeBSD default
  ansible.builtin.set_fact:
    cron_daily: /usr/local/etc/periodic/daily/
    # sh from FreeBSD supports pipefail option
    default_shell: /bin/sh
    etc_prefix: /usr/local
    install_prefix: /usr/local
  when: ansible_os_family == "FreeBSD"
